name: STARZ
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter



  pinput: ^3.0.1
  http: ^0.13.6
  multiple_result:
  fluttertoast: ^8.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_svg: ^2.0.9
  emoji_picker_flutter: ^1.5.2
  socket_io_client: ^2.0.1
  whatsapp: ^2.0.0
  get: ^4.6.5
  get_storage: ^2.0.3
  intl: ^0.19.0
  flutter_facebook_auth: ^5.0.7
  file_picker: ^6.1.1
  image_picker: ^1.0.5
  cached_network_image: ^3.2.3
  flutter_contacts: ^1.1.6
  sizer: ^2.0.15
  video_player: ^2.5.2
  permission_handler: ^11.1.0
  flutter_sound: ^9.2.13
  rxdart: ^0.27.7
  #audioplayers: ^5.2.1
  just_audio: ^0.9.31
  swipe_to: ^1.0.2
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.5
  location: ^5.0.3
  place_picker: ^0.10.0
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.2
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  cloud_firestore: ^4.13.2
  firebase_storage: ^11.5.2
  dio: ^5.3.4
  http_parser: ^4.0.2
  flutter_pdfview: ^1.3.2
  google_fonts: ^4.0.4
  linked_scroll_controller: ^0.2.0
  #advance_pdf_viewer: ^2.0.1
  universal_html: ^2.2.4
  flutter_cache_manager: ^3.3.1
  flutter_cached_pdfview: ^0.4.2
  path_provider: ^2.1.1
  advance_pdf_viewer2: ^2.0.5+1
  flutter_local_notifications: ^16.3.0
  firebase_messaging: ^14.7.9
  flutter_downloader: ^1.11.6
  open_file: ^3.3.2
  camera: ^0.10.5+7
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.0.1
  mockito: ^5.4.4
  connectivity: ^3.0.6
  provider: ^6.1.1
  image_gallery_saver: ^2.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  twemoji: ^0.1.0
  fl_chart: ^0.66.1
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  syncfusion_flutter_charts: ^24.1.47+1
  flutter_animated_dialog: ^2.0.1
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  contacts_service: ^0.6.3
  photo_view: ^0.14.0
  in_app_update: ^4.2.2
  scrollable_positioned_list: ^0.3.8
  grouped_list: ^5.1.2
  alphabet_scroll_view: ^0.3.2
  scroll_to_index: ^3.0.1
  libphonenumber: ^2.0.2
  chewie: ^1.7.5
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.4
  freezed: ^2.3.2
  flutter_lints: ^3.0.1


flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo.png'
  min_sdk_android: 21
  remove_alpha_ios: true

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
